# Generated by Django 3.1.1 on 2020-09-16 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('contact_email', models.EmailField(max_length=200)),
                ('whose', models.CharField(choices=[('H', 'Husband'), ('W', 'Wife')], max_length=1)),
                ('status', models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('M', 'Maybe')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_title', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('contact_email', models.EmailField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
                ('web_site', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('occupation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='weddings.occupation')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('number', models.IntegerField()),
                ('special_note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('I', 'Important'), ('U', 'Urgent'), ('R', 'Rest')], default='R', max_length=1)),
                ('status', models.CharField(choices=[('D', 'Done'), ('I', 'In Progress'), ('N', 'Not Started')], default='N', max_length=1)),
                ('due_to', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Wedding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('husband', models.CharField(max_length=200)),
                ('wife', models.CharField(max_length=200)),
                ('special_date', models.DateField(blank=True, null=True)),
                ('guests', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='weddings.guest')),
                ('suppliers', models.ManyToManyField(to='weddings.Supplier')),
                ('tasks', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='weddings.task')),
            ],
        ),
        migrations.AddField(
            model_name='guest',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='weddings.table'),
        ),
    ]
