# Generated by Django 3.1.1 on 2020-09-25 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weddings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_title', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='guest',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='allergy',
            field=models.CharField(choices=[('Lac', 'Lactose'), ('Egg', 'Eggs'), ('Soy', 'Soya'), ('Nut', 'Nuts and Seeds'), ('Glu', 'Gluten'), ('Fis', 'Fish'), ('Veg', 'Vegetables'), ('Fru', 'Fruits'), ('Mea', 'Meat'), ('Non', 'None')], default='Non', max_length=3),
        ),
        migrations.AddField(
            model_name='guest',
            name='children',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='weddings.guest'),
        ),
        migrations.AddField(
            model_name='guest',
            name='comment',
            field=models.TextField(default='No comments'),
        ),
        migrations.AddField(
            model_name='guest',
            name='hotel_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='status',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('M', 'Maybe'), ('U', 'Unknown')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='guest',
            name='whose',
            field=models.CharField(choices=[('G', 'Groom'), ('B', 'Bride')], default='B', max_length=1),
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_title', models.CharField(max_length=200)),
                ('expected_payment', models.IntegerField()),
                ('resulted_payment', models.IntegerField()),
                ('amount_paid', models.IntegerField()),
                ('amount_to_go', models.IntegerField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='weddings.category')),
                ('supplier_in_connect', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='weddings.supplier')),
            ],
        ),
        migrations.AddField(
            model_name='supplier',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='weddings.location'),
        ),
    ]
