# Generated by Django 3.1.1 on 2020-10-11 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weddings', '0002_auto_20200925_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='cost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='weddings.budget'),
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(default='description is required'),
        ),
    ]
