# Generated by Django 3.1.1 on 2020-10-11 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weddings', '0003_auto_20201011_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='amount_paid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='amount_to_go',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='resulted_payment',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='occupation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='weddings.category'),
        ),
        migrations.DeleteModel(
            name='Occupation',
        ),
    ]
